name: Sync

on:
  push:
    branches:
      - api-sync

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  api_sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        endpoint: [registry.cn-hongkong.aliyuncs.com]
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: registry.cn-hongkong.aliyuncs.com
        username: q2889895155
        password: ${{ secrets.ALIYUN_CR_PASSWORD }}
    - uses: docker/login-action@v2
      with:
        registry: registry.cn-shenzhen.aliyuncs.com
        username: q2889895155
        password: ${{ secrets.ALIYUN_CR_PASSWORD }}
    - uses: docker/login-action@v2
      with:
        registry: swr.ap-southeast-1.myhuaweicloud.com
        username: ap-southeast-1@RY0U3RFXDOXU9JXGXWM1
        password: ${{ secrets.HUAWEI_SWR_PASSWORD }}
    - name: Run
      env:
        FROM_IMAGE: __FROM_IMAGE__
        TO_IMAGE: __TO_IMAGE__
      run: |
        docker pull $FROM_IMAGE
        docker tag $FROM_IMAGE ${{ matrix.endpoint }}/$TO_IMAGE
        docker push ${{ matrix.endpoint }}/$TO_IMAGE
