name: Fastadmin Sync

on:
  push:
    branches:
      - fastadmin-sync
#v=1

jobs:
  base:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3
    - uses: wei/git-sync@v3
      with:
        source_repo: "git@gitee.com:fastadminnet/framework.git"
        source_branch: "master"
        destination_repo: "git@github.com:hongfs/hongfs.git"
        destination_branch: "fastadmin-framework"
        source_ssh_private_key: ${{ secrets.FASTADMIN_SYNC_GITEE_PRIVATE_KEY }}
        destination_ssh_private_key: ${{ secrets.FASTADMIN_SYNC_GITHUB_PRIVATE_KEY }}
