name: Sync

on:
  push:
    branches:
      - api-sync

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  api_sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [cn-hongkong, cn-shenzhen]
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: registry.cn-hongkong.aliyuncs.com
        username: q2889895155
        password: ${{ secrets.ALIYUN_CR_PASSWORD }}
    - uses: docker/login-action@v2
      with:
        registry: registry.cn-shenzhen.aliyuncs.com
        username: q2889895155
        password: ${{ secrets.ALIYUN_CR_PASSWORD }}
    - name: Run
      env:
        FROM_IMAGE: hongfs/env:web-1
        TO_IMAGE: hongfs/env:web-1
      run: |
        docker pull -q ghcr.io/$FROM_IMAGE
        docker tag ghcr.io/$FROM_IMAGE registry.${{ matrix.region }}.aliyuncs.com/$TO_IMAGE
        docker push -q registry.${{ matrix.region }}.aliyuncs.com/$TO_IMAGE
