name: Sync

on:
  push:
    branches:
      - image-sync
  schedule:
    - cron: "30 0 * * *" # 北京时间每天 08:30

jobs:
  base:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: hongfs
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - uses: docker/login-action@v2
      with:
        registry: registry.cn-hongkong.aliyuncs.com
        username: q2889895155
        password: ${{ secrets.ALIYUN_CR_PASSWORD }}
    - uses: docker/login-action@v2
      with:
        registry: registry.cn-shenzhen.aliyuncs.com
        username: q2889895155
        password: ${{ secrets.ALIYUN_CR_PASSWORD }}
    - name: Run
      run: |
        export
        cd "${GITHUB_WORKSPACE}"
        chmod +x ./run.sh
        chmod +x ./sync.sh
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    needs:
      - base
    strategy:
      matrix:
        info:
          - from: "golang"
            to: "registry.cn-hongkong.aliyuncs.com/hongfs/golang"
          - from: "golang"
            to: "registry.cn-shenzhen.aliyuncs.com/hongfs/golang"
    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: |
        export
        echo ${{ matrix.info.from }}
        echo ${{ matrix.info.to }}
        echo ${{ github.ref }}
