name: Fastadmin Sync

on:
  push:
    branches:
      - fastadmin-sync

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: RUN
      run: |
        git branch
        git remote add fastadmin https://gitee.com/fastadminnet/framework.git
        git fetch fastadmin
        git pull fastadmin-data fastadmin