name: Sync

on:
  push:
    branches:
      - image-sync

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  library:
    runs-on: ubuntu-latest
    needs:
      - base
    services:
      get-docker-tags:
        image: ghcr.io/hongfs/env:get-docker-tags
        ports:
          - 9000:9000
    strategy:
      max-parallel: 8
      matrix:
        info:
          - from: "golang"
            to: "registry.cn-hongkong.aliyuncs.com/hongfs/golang"
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: hongfs
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - uses: docker/login-action@v2
      with:
        registry: registry.cn-hongkong.aliyuncs.com
        username: q2889895155
        password: ${{ secrets.ALIYUN_CR_PASSWORD }}
    - name: Run
      run: |
        curl -v "http://get-docker-tags/get?name=${{ matrix.info.from }}"
        cd "${GITHUB_WORKSPACE}"
        chmod +x ./sync.sh
        FROM=${{ matrix.info.from }} TO=${{ matrix.info.to }} ./sync.sh
