name: Fastadmin Sync

on:
  push:
    branches:
      - fastadmin-sync

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: RUN
      run: |
        git branch
        git remote add gitee git@gitee.com:fastadminnet/framework.git
        git branch -M fastadmin
        git push -u gitee fastadmin