name: Sync

on:
  push:
    branches:
      - image-sync
  schedule:
    - cron: "30 0,5,12 * * *" # 北京时间每天 08/13/20:30

# 已注释程序的同步

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ghcr_env:
    runs-on: ubuntu-latest
    services:
      get-docker-tags:
        image: ghcr.io/hongfs/env:get-docker-tags
        ports:
          - 9000:9000
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: hongfs
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Run
      run: |
        cd "${GITHUB_WORKSPACE}"
        chmod +x ./sync.sh
        TO=hongfs/env FROM=ghcr.io/hongfs/env ./sync.sh
