name: Fastadmin Sync

on:
  push:
    branches:
      - fastadmin-sync

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: RUN
      run: |
        sudo mkdir -p ~/.ssh/
        sudo echo "${{ secrets.FASTADMIN_SYNC_GITEE_PRIVATE_KEY }}" >> ~/.ssh/src_rsa
        sudo chmod 600 ~/.ssh/src_rsa
        sudo git remote add fastadmin git@gitee.com:fastadminnet/framework.git
        sudo git branch -M fastadmin-framework
        sudo git push -u fastadmin fastadmin-framework
