name: Ecs Price Sync

on:
  push:
    branches:
      - ecs_price_sync

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ghcr_env:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [1,2,3,4,5]
    steps:
    - name: Run
      env:
        CONFIG_KEY: ${{ secrets.SPOT_KEY }}
      run: |
        podman run -it -e CONFIG_KEY="${{ env.CONFIG_KEY }}" registry.cn-hongkong.aliyuncs.com/hongfs/aliyun-ecs-spot-price:main
