name: Fastadmin Sync

on:
  push:
    branches:
      - fastadmin-sync

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: RUN
      run: |
        echo $USER
        pwd
        mkdir -p ~/.ssh/
        echo "${{ secrets.FASTADMIN_SYNC_GITEE_PRIVATE_KEY }}" | sed 's/\\n/\n/g' > ~/.ssh/src_rsa
        chmod 600 ~/.ssh/src_rsa
        git remote add fastadmin git@gitee.com:fastadminnet/framework.git
        git branch -M fastadmin-framework
        git push -u fastadmin fastadmin-framework
