name: Sync

on:
  push:
    branches:
      - image-sync
  schedule:
    - cron: "30 0,5,12 * * *" # 北京时间每天 08/13/20:30

# 已注释程序的同步

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  metersphere:
    runs-on: ubuntu-latest
    needs:
      - base
    services:
      get-docker-tags:
        image: ghcr.io/hongfs/env:get-docker-tags
        ports:
          - 9000:9000
    strategy:
      matrix:
        name: [test-track,system-setting,report-stat,project-management,performance-test,api-test,gateway,eureka,data-streaming,node-controller,ui-test,workstation,jmeter-master]
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: hongfs
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - uses: docker/login-action@v2
      with:
        registry: registry.cn-qingdao.aliyuncs.com
        username: q2889895155
        password: ${{ secrets.ALIYUN_CR_PASSWORD }}
    # - name: Run
    #   run: |
    #     cd "${GITHUB_WORKSPACE}"
    #     chmod +x ./sync.sh
    #     FROM=registry.cn-qingdao.aliyuncs.com/metersphere/${{ matrix.name }} TO=hongfs/${{ matrix.name }} ./sync.sh
  runnergo:
    runs-on: ubuntu-latest
    needs:
      - base
    services:
      get-docker-tags:
        image: ghcr.io/hongfs/env:get-docker-tags
        ports:
          - 9000:9000
    strategy:
      matrix:
        name: [manage,web-ui,engine,file-server,collector,kafka,mysql,redis,mongo,zookeeper,manage-ws]
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: hongfs
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - uses: docker/login-action@v2
      with:
        registry: registry.cn-beijing.aliyuncs.com
        username: q2889895155
        password: ${{ secrets.ALIYUN_CR_PASSWORD }}
    # - name: Run
    #   run: |
    #     cd "${GITHUB_WORKSPACE}"
    #     chmod +x ./sync.sh
    #     FROM=registry.cn-beijing.aliyuncs.com/runnergo/${{ matrix.name }} TO=hongfs/runnergo_${{ matrix.name }} ./sync.sh
  aliyun_acs:
    runs-on: ubuntu-latest
    needs:
      - base
    services:
      get-docker-tags:
        image: ghcr.io/hongfs/env:get-docker-tags
        ports:
          - 9000:9000
    strategy:
      matrix:
        name: [csi-node-driver-registrar,csi-plugin,csi-provisioner,autoscaler]
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: hongfs
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - uses: docker/login-action@v2
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: q2889895155
        password: ${{ secrets.ALIYUN_CR_PASSWORD }}
    # - name: Run
    #   run: |
    #     cd "${GITHUB_WORKSPACE}"
    #     chmod +x ./sync.sh
    #     FROM=registry.cn-hangzhou.aliyuncs.com/acs/${{ matrix.name }} TO=hongfs/${{ matrix.name }} ./sync.sh
  ghcr_env:
    runs-on: ubuntu-latest
    needs:
      - base
    services:
      get-docker-tags:
        image: ghcr.io/hongfs/env:get-docker-tags
        ports:
          - 9000:9000
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: hongfs
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Run
      run: |
        cd "${GITHUB_WORKSPACE}"
        chmod +x ./sync.sh
        TO=hongfs/env FROM=ghcr.io/hongfs/env ./sync.sh
