name: Ecs Price Sync

on:
  push:
    branches:
      - ecs_price_sync

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ghcr_env:
    runs-on: ubuntu-latest
    steps:
    - name: Run
      run: |
        podman run -it -e CONFIG_KEY=${{ secrets.SPOT_KEY }} registry.cn-hongkong.aliyuncs.com/hongfs/aliyun-ecs-spot-price:main
