name: Sync

on:
  push:
    branches:
      - image-sync
  schedule:
    - cron: "30 0,5,12 * * *" # 北京时间每天 08/13/20:30

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  library:
    runs-on: ubuntu-latest
    needs:
      - base
    strategy:
      max-parallel: 8
      matrix:
        info:
          - from: "minio/minio"
            to: "registry.cn-hongkong.aliyuncs.com/hongfs/minio"
          - from: "golang"
            to: "registry.cn-hongkong.aliyuncs.com/hongfs/golang"
          - from: "golang"
            to: "registry.cn-shenzhen.aliyuncs.com/hongfs/golang"
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: hongfs
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - uses: docker/login-action@v2
      with:
        registry: registry.cn-hongkong.aliyuncs.com
        username: q2889895155
        password: ${{ secrets.ALIYUN_CR_PASSWORD }}
    - uses: docker/login-action@v2
      with:
        registry: registry.cn-shenzhen.aliyuncs.com
        username: q2889895155
        password: ${{ secrets.ALIYUN_CR_PASSWORD }}
    - name: Run
      run: |
        cd "${GITHUB_WORKSPACE}"
        chmod +x ./sync.sh
        FROM=${{ matrix.info.from }} TO=${{ matrix.info.to }} ./sync.sh
  metersphere:
    runs-on: ubuntu-latest
    needs:
      - base
    strategy:
      max-parallel: 8
      matrix:
        name: [test-track,system-setting,report-stat,project-management,performance-test,api-test,gateway,eureka,data-streaming,node-controller,ui-test,workstation,jmeter-master]
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: hongfs
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - uses: docker/login-action@v2
      with:
        registry: registry.cn-qingdao.aliyuncs.com
        username: q2889895155
        password: ${{ secrets.ALIYUN_CR_PASSWORD }}
    - name: Run
      run: |
        cd "${GITHUB_WORKSPACE}"
        chmod +x ./sync.sh
        FROM=registry.cn-qingdao.aliyuncs.com/metersphere/${{ matrix.name }} TO=hongfs/${{ matrix.name }} ./sync.sh
