name: Sync

on:
  push:
    branches:
      - image-sync
  schedule:
    - cron: "30 0 * * *" # 北京时间每天 08:30

jobs:
  base:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: hongfs
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - uses: docker/login-action@v2
      with:
        registry: registry.cn-hongkong.aliyuncs.com
        username: q2889895155
        password: ${{ secrets.ALIYUN_CR_PASSWORD }}
    - uses: docker/login-action@v2
      with:
        registry: registry.cn-shenzhen.aliyuncs.com
        username: q2889895155
        password: ${{ secrets.ALIYUN_CR_PASSWORD }}
    - name: Run
      run: |
        cd "${GITHUB_WORKSPACE}"
        chmod +x ./sync.sh
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    needs:
      - base
    strategy:
      matrix:
        info:
          - from: "golang"
            to: "registry.cn-hongkong.aliyuncs.com/hongfs/golang"
          - from: "golang"
            to: "registry.cn-shenzhen.aliyuncs.com/hongfs/golang"
          - from: "test-track"
            to: "registry.cn-qingdao.aliyuncs.com/metersphere/test-track"
          - from: "system-setting"
            to: "registry.cn-qingdao.aliyuncs.com/metersphere/system-setting"
          - from: "report-stat"
            to: "registry.cn-qingdao.aliyuncs.com/metersphere/report-stat"
          - from: "project-management"
            to: "registry.cn-qingdao.aliyuncs.com/metersphere/project-management"
          - from: "performance-test"
            to: "registry.cn-qingdao.aliyuncs.com/metersphere/performance-test"
          - from: "api-test,gateway"
            to: "registry.cn-qingdao.aliyuncs.com/metersphere/api-test,gateway"
          - from: "eureka"
            to: "registry.cn-qingdao.aliyuncs.com/metersphere/eureka"
          - from: "data-streaming"
            to: "registry.cn-qingdao.aliyuncs.com/metersphere/data-streaming"
          - from: "node-controller"
            to: "registry.cn-qingdao.aliyuncs.com/metersphere/node-controller"
          - from: "ui-test"
            to: "registry.cn-qingdao.aliyuncs.com/metersphere/ui-test"
          - from: "workstation"
            to: "registry.cn-qingdao.aliyuncs.com/metersphere/workstation"
    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: |
        cd "${GITHUB_WORKSPACE}"
        FROM=${{ matrix.info.from }} TO=${{ matrix.info.to }} ./sync.sh
